apiVersion: v1
kind: Pod
metadata:
  name: python-pod
spec:
  containers:
    - name: python
      image: python:3.9
      command:
        - /bin/sh
        - -ec
        - |
          sleep infinity