apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-exec
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups: [ "" ]
    resources:
      - pods/exec
    verbs:
      - create
      - get