apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-k8s-client
roleRef:
  kind: Role
  name: pods-exec
  apiGroup: rbac.authorization.k8s.io